
scrapers:
  - name: remoteok
    type: static
    limit: 1000
  - name: jobspresso
    type: selenium
    limit: 1000
  - name: remotive-selenium
    type: selenium
    limit: 1000

storage:
  db_path: data_output/jobs.db
  export_csv: data_output/jobs.csv
  export_json: data_output/jobs.json
  export_excel: data_output/jobs.xlsx
